# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: 'build'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      submodules: true
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        set tessprefix=%CD%\metabuild\tesseract-x86
        mkdir metabuild\build-x86
        pushd metabuild\build-x86
        call ..\..\build.bat
      displayName: 'build x86'

    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set tessprefix=%CD%\metabuild\tesseract-amd64
        mkdir metabuild\build-amd64
        pushd metabuild\build-amd64
        call ..\..\build.bat
      displayName: 'build x64'

    - script: |
        cd metabuild
        mkdir win-amd64\bin
        mkdir win-x86\bin
        xcopy tesseract-amd64\bin win-amd64\bin
        xcopy tesseract-x86\bin win-x86\bin
        copy /y ..\tesseract-mini-bin.nuspec .
      displayName: 'prepare nuget'

    - task: NuGetCommand@2
      displayName: 'nuget pack'
      inputs:
        command: 'pack'
        packagesToPack: 'metabuild/tesseract-mini-bin.nuspec'
        versioningScheme: 'off'
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\'
        artifact: 'NuGet packages'
        publishLocation: 'pipeline'